<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use League\OAuth2\Server\Repositories\ClientRepositoryInterface;
use App\Entity\Client;

class ClientRepository extends EntityRepository implements ClientRepositoryInterface
{
    /**
     * Determine if the given client can handle the given grant type.
     */
    public function handlesGrant($client, $grantType)
    {
        return $client->getGrants();
    }

    /**
     * Get an active client by the given ID.
     */
    public function findActive($clientIdentifier)
    {
        // TODO filter yang aktif saja
        return $this->findOneByIdentifier($clientIdentifier);
    }

    /**
     * {@inheritdoc}
     */
    public function getClientEntity(
      $clientIdentifier,
      $grantType,
      $clientSecret = null,
      $mustValidateSecret = true)
    {
        // First, we will verify that the client exists and is authorized to create personal
        // access tokens. Generally personal access tokens are only generated by the user
        // from the main interface. We'll only let certain clients generate the tokens.
        $client = $this->findActive($clientIdentifier);

        if (! $client || ! $this->handlesGrant($client, $grantType)) {
            return;
        }

        // Once we have an existing client record we will create this actual client instance
        // and verify the secret if necessary. If the secret is valid we will be ready to
        // return this client instance back out to the consuming methods and finish up.

        if ($mustValidateSecret &&
            ! hash_equals($client->getSecret(), (string) $clientSecret)) {
            return;
        }

        return $client;
    }
}
